### ISSUE TITLE
[1.12.2] Startup Crash -- No Class Def Found

### ISSUE THREAD

**Issue by ElvenChaos** [MinecraftModDevelopment/EndMetals#14]
On startup, I get this crash: https://pastebin.com/H4vUTtGx

MC: 1.12.2
Forge: 14.23.0.2495
End Metals: 1.2.0-beta1.1

**Comment by dshadowwolf** [comment]
Okay, I'm going to blame Eclipse for deciding to auto-import the wrong thing. New build will be coming when I've got the issues with the Tinkers' Construct integration figured out.

**Comment by dshadowwolf** [comment]
There is a PR for BaseMetals that fixes the root cause of this - it's awaiting some of the MMD Team to review it for logic bugs and things that can be done better.

**Comment by dshadowwolf** [comment]
okay - new versions of the entire spread are (or will soon be) on Curse - let us know if you get the crash with the new versions.

**Comment by ElvenChaos** [comment]
No crashes, all good.

**Comment by dshadowwolf** [comment]
awesome, means that the extra work I put in to add extra error checks and protection - along with the updates to the Tinkers' Construct interface - fixed things.
